workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - code_signing # Fait le lien avec vos certificats de l'interface

    scripts:
      - name: Install dependencies
        script: | 
          flutter packages pub get
          find . -name "Podfile" -execdir pod install --repo-update
      - name: Build IPA
        script: | 
          flutter build ipa --release --flavor ios-production

    artifacts:
      - build/ios/ipa/*.ipa

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID