workflows:
  default-workflow:
    name: Default Workflow
    instance_type: mac_mini_m2
    environment:
      flutter: stable
      xcode: latest
      cocoapods: default
      groups:
        - code_signing # Fait le lien avec vos certificats de l'interface

    scripts:
      - name: Get Flutter dependencies
        script: | 
          flutter clean
          flutter pub get
          
      - name: Generate iOS build files
        script: |
          # Force la génération des fichiers de configuration iOS
          flutter build ios --config-only --no-codesign
          
      - name: Verify generated files
        script: |
          echo "Vérification des fichiers générés:"
          ls -la ios/Flutter/
          if [ ! -f "ios/Flutter/Generated.xcconfig" ]; then
            echo "❌ Generated.xcconfig manquant"
            exit 1
          else
            echo "✅ Generated.xcconfig trouvé"
            cat ios/Flutter/Generated.xcconfig
          fi
          
      - name: Install pods
        script: | 
          cd ios
          pod install --repo-update
          
      - name: Build IPA
        script: | 
          flutter build ipa --release --flavor ios-production

    artifacts:
      - build/ios/ipa/*.ipa
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/Products/Release-iphoneos/*.dSYM

    publishing:
      app_store_connect:
        api_key: $APP_STORE_CONNECT_PRIVATE_KEY
        key_id: $APP_STORE_CONNECT_KEY_ID
        issuer_id: $APP_STORE_CONNECT_ISSUER_ID