// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDqxpWNFeUCEYewA9doKDqH08RbFZzahFc',
    appId: '1:524478716523:web:046e9ea4998373213fef2e',
    messagingSenderId: '524478716523',
    projectId: 'adomed-chatbot-nouveau',
    authDomain: 'adomed-chatbot-nouveau.firebaseapp.com',
    storageBucket: 'adomed-chatbot-nouveau.firebasestorage.app',
    measurementId: 'G-XL7L9RJYF4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1MDKxGCA3tQEChZ3m7KrDMm19aA4LIhE',
    appId: '1:524478716523:android:3d3100afceb41fe33fef2e',
    messagingSenderId: '524478716523',
    projectId: 'adomed-chatbot-nouveau',
    storageBucket: 'adomed-chatbot-nouveau.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC8_kGGSXqZI5ZLXo_TAAlDdzvxXdY1l-k',
    appId: '1:524478716523:ios:9b16213d6ee811c53fef2e',
    messagingSenderId: '524478716523',
    projectId: 'adomed-chatbot-nouveau',
    storageBucket: 'adomed-chatbot-nouveau.firebasestorage.app',
    iosBundleId: 'com.example.adomedApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC8_kGGSXqZI5ZLXo_TAAlDdzvxXdY1l-k',
    appId: '1:524478716523:ios:9b16213d6ee811c53fef2e',
    messagingSenderId: '524478716523',
    projectId: 'adomed-chatbot-nouveau',
    storageBucket: 'adomed-chatbot-nouveau.firebasestorage.app',
    iosBundleId: 'com.example.adomedApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDqxpWNFeUCEYewA9doKDqH08RbFZzahFc',
    appId: '1:524478716523:web:046e9ea4998373213fef2e',
    messagingSenderId: '524478716523',
    projectId: 'adomed-chatbot-nouveau',
    authDomain: 'adomed-chatbot-nouveau.firebaseapp.com',
    storageBucket: 'adomed-chatbot-nouveau.firebasestorage.app',
    measurementId: 'G-XL7L9RJYF4',
  );

}